=== leadVisionary/DEPTHS/DEPTHS/DEPTHS/Tomcat/resources/xml/LOM_shema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp1 U (http://www.xmlspy.com) by any (Ru-Board) -->
<!-- edited with XMLSPY v5 U (http://www.xmlspy.com) by Registred (Registred) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="LOM">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Concept" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="conceptGeneralInformation">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="title" type="xs:string"/>
										<xs:element name="identifier" type="xs:ID"/>
										<xs:element name="prerequisite" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="minKnowledgeLevel">
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:minInclusive value="1"/>
													<xs:maxInclusive value="5"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="type" type="xs:string"/>
										<xs:element name="ordinalNumber" type="xs:integer"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Unit" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="unitGeneralInformation">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="title" type="xs:string"/>
													<xs:element name="ordinalNumber" type="xs:integer"/>
													<xs:element name="identifier" type="xs:ID"/>
													<xs:element name="difficultyLevel" type="xs:integer"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Fragment" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="title" type="xs:string"/>
													<xs:element name="identifier" type="xs:ID"/>
													<xs:element name="type">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="programmingLanguage" type="xs:string"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="detailLevel">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:minInclusive value="1"/>
																<xs:maxInclusive value="3"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="difficultyLevel" type="xs:integer"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Questions" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="group" type="xs:integer"/>
										<xs:element name="identifier" type="xs:ID"/>
										<xs:element name="difficultyLevel" type="xs:integer"/>
										<xs:element name="related-to" type="xs:IDREF"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="concNumber" type="xs:int"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="difficultyType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="very easy"/>
			<xs:enumeration value="easy"/>
			<xs:enumeration value="medium"/>
			<xs:enumeration value="difficult"/>
			<xs:enumeration value="very difficult"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== leadVisionary/DEPTHS/DEPTHS/DEPTHS/Tomcat/resources/xml/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<LOM xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LOM_shema.xsd" concNumber="24">
    <Concept>
        <conceptGeneralInformation>
            <title>Abstract Factory</title>
            <identifier>c101</identifier>
            <prerequisite>0</prerequisite>
            <minKnowledgeLevel>1</minKnowledgeLevel>
            <type>Creational</type>
            <ordinalNumber>1</ordinalNumber>
        </conceptGeneralInformation>
        <Unit>
            <unitGeneralInformation>
                <title>Introduction</title>
                <ordinalNumber>1</ordinalNumber>
                <identifier>u1011</identifier>
                <difficultyLevel>1</difficultyLevel>
            </unitGeneralInformation>
            <Fragment>
                <title>Intent</title>
                <identifier>f10111</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Also Known As</title>
                <identifier>f10112</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Motivation</title>
                <identifier>f10113</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Motivation</title>
                <identifier>f10114</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Motivation</title>
                <identifier>f10115</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>2</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Motivation</title>
                <identifier>f10116</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>3</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Motivation</title>
                <identifier>f10117</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>3</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Applicability</title>
                <identifier>f10118</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Applicability</title>
                <identifier>f10119</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Applicability</title>
                <identifier>f101110</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>2</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Applicability</title>
                <identifier>f101111</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>2</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Applicability</title>
                <identifier>f101112</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>2</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
        </Unit>
        <Unit>
            <unitGeneralInformation>
                <title>Structure</title>
                <ordinalNumber>2</ordinalNumber>
                <identifier>u1012</identifier>
                <difficultyLevel>1</difficultyLevel>
            </unitGeneralInformation>
            <Fragment>
                <title>Structure</title>
                <identifier>f10121</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
        </Unit>
        <Unit>
            <unitGeneralInformation>
                <title>Participants and Collaborations</title>
                <ordinalNumber>3</ordinalNumber>
                <identifier>u1013</identifier>
                <difficultyLevel>1</difficultyLevel>
            </unitGeneralInformation>
            <Fragment>
                <title>Participants</title>
                <identifier>f10131</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Participants</title>
                <identifier>f10132</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Participants</title>
                <identifier>f10133</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>2</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Participants</title>
                <identifier>f10134</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Participants</title>
                <identifier>f10135</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>2</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Participants</title>
                <identifier>f10136</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Participants</title>
                <identifier>f10137</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>2</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Participants</title>
                <identifier>f10138</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Participants</title>
                <identifier>f10139</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>2</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Participants</title>
                <identifier>f101310</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>2</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Participants</title>
                <identifier>f101311</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Participants</title>
                <identifier>f101312</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>2</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Collaborations</title>
                <identifier>f101313</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Collaborations</title>
                <identifier>f101314</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
            <Fragment>
                <title>Collaborations</title>
                <identifier>f101315</identifier>
                <type programmingLanguage="any"/>
                <detailLevel>1</detailLevel>
                <difficultyLevel>1</difficultyLevel>
            </Fragment>
        </Unit>
        <Unit>
            <unitGeneralInformation>
                <title>Consequences</title>
                <ordinalNumber>4</ordinalNumber>
                <identifier>u1014</identifier>
                <difficultyLevel>1</difficultyLevel>
            </unitGeneralInformation>
