=== leadVisionary/DEPTHS/DEPTHS/DEPTHS/DEPTHS/resources/xml/DomainModule_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp1 U (http://www.xmlspy.com) by any (Ru-Board) -->
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Jeremic Zoran (nn) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="difficultyType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="very easy"/>
			<xs:enumeration value="easy"/>
			<xs:enumeration value="medium"/>
			<xs:enumeration value="difficult"/>
			<xs:enumeration value="very difficult"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Course">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Concept" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="conceptGeneralInformation">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="identifier" type="xs:ID"/>
										<xs:element name="title" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Unit" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="unitGeneralInformation">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="identifier" type="xs:ID"/>
													<xs:element name="title" type="xs:string"/>
													<xs:element name="difficultyLevel" type="xs:integer"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Fragment" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="identifier" type="xs:ID"/>
													<xs:element name="type" type="xs:string"/>
													<xs:element name="detailLevel" type="xs:integer"/>
													<xs:element name="title" type="xs:string"/>
													<xs:element name="content" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Questionare" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="testGeneralInformation">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="identifier" type="xs:ID"/>
													<xs:element name="difficultyLevel" type="xs:integer"/>
													<xs:element name="related-to" type="xs:IDREF"/>
													<xs:element name="group" type="xs:integer"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Question" type="xs:string"/>
										<xs:element name="Answer" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="truth" type="xs:boolean"/>
													<xs:element name="textOfAnswer" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== leadVisionary/DEPTHS/DEPTHS/DEPTHS/DEPTHS/resources/xml/example_domain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Course SYSTEM "CourseDTD.dtd">
<Course xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DomainModule_Schema.xsd">
    <Concept>
        <conceptGeneralInformation>
            <identifier>c101</identifier>
            <title>Abstract Factory</title>
        </conceptGeneralInformation>
        <Unit>
            <unitGeneralInformation>
                <identifier>u1011</identifier>
                <title>Introduction</title>
                <difficultyLevel>1</difficultyLevel>
            </unitGeneralInformation>
            <Fragment>
                <identifier>f10111</identifier>
                <type>whole</type>
                <detailLevel>1</detailLevel>
                <title>Intent</title>
                <content>Provide an interface for creating families of related or dependent objects without specifying their concrete classes.</content>
            </Fragment>
            <Fragment>
                <identifier>f10112</identifier>
                <type>whole</type>
                <detailLevel>1</detailLevel>
                <title>Also Known As</title>
                <content>Kit</content>
            </Fragment>
            <Fragment>
                <identifier>f10113</identifier>
                <type>first</type>
                <detailLevel>1</detailLevel>
                <title>Motivation</title>
                <content>Consider a user interface toolkit that supports multiple look-and-feel standards, such as Motif and Presentation Manager. Different look-and-feels define different appearances and behaviors for user interface "widgets" like scroll bars, windows, and buttons. To be portable across look-and-feel standards, an application should not hard-code its widgets for a particular look and feel. Instantiating look-and-feel-specific classes of widgets throughout the application makes it hard to change the look and feel later.

</content>
            </Fragment>
            <Fragment>
                <identifier>f10114</identifier>
                <type>part-of</type>
                <detailLevel>1</detailLevel>
                <title>Motivation</title>
                <content>We can solve this problem by defining an abstract WidgetFactory class that declares an interface for creating each basic kind of widget. There's also an abstract class for each kind of widget, and concrete subclasses implement widgets for specific look-and-feel standards. WidgetFactory's interface has an operation that returns a new widget object for each abstract widget class. Clients call these operations to obtain widget instances, but clients aren't aware of the concrete classes they're using. Thus clients stay independent of the prevailing look and feel.

</content>
            </Fragment>
            <Fragment>
                <identifier>f10115</identifier>
                <type>picture_middle</type>
                <detailLevel>2</detailLevel>
                <title>Motivation</title>
                <content>AbstractFactory_01</content>
            </Fragment>
            <Fragment>
                <identifier>f10116</identifier>
                <type>part-of</type>
                <detailLevel>3</detailLevel>
                <title>Motivation</title>
                <content>There is a concrete subclass of WidgetFactory for each look-and-feel standard. Each subclass implements the operations to create the appropriate widget for the look and feel. For example, the CreateScrollBar operation on the MotifWidgetFactory instantiates and returns a Motif scroll bar, while the corresponding operation on the PMWidgetFactory returns a scroll bar for Presentation Manager. Clients create widgets solely through the WidgetFactory interface and have no knowledge of the classes that implement widgets for a particular look and feel. In other words, clients only have to commit to an interface defined by an abstract class, not a particular concrete class.

</content>
            </Fragment>
            <Fragment>
                <identifier>f10117</identifier>
                <type>part-of</type>
                <detailLevel>3</detailLevel>
                <title>Motivation</title>
                <content>A WidgetFactory also enforces dependencies between the concrete widget classes. A Motif scroll bar should be used with a Motif button and a Motif text editor, and that constraint is enforced automatically as a consequence of using a MotifWidgetFactory.

</content>
            </Fragment>
            <Fragment>
                <identifier>f10118</identifier>
                <type>first</type>
                <detailLevel>1</detailLevel>
                <title>Applicability</title>
                <content>Use the Abstract Factory pattern when</content>
            </Fragment>
            <Fragment>
                <identifier>f10119</identifier>
                <type>list2</type>
                <detailLevel>1</detailLevel>
                <title>Applicability</title>
                <content>a system should be independent of how its products are created, composed, and represented. </content>
            </Fragment>
            <Fragment>
                <identifier>f101110</identifier>
                <type>list2</type>
                <detailLevel>2</detailLevel>
                <title>Applicability</title>
                <content>a system should be configured with one of multiple families of products. </content>
            </Fragment>
            <Fragment>
                <identifier>f101111</identifier>
                <type>list2</type>
                <detailLevel>2</detailLevel>
                <title>Applicability</title>
                <content>a family of related product objects is designed to be used together, and you need to enforce this constraint. </content>
            </Fragment>
            <Fragment>
                <identifier>f101112</identifier>
                <type>list2</type>
                <detailLevel>2</detailLevel>
                <title>Applicability</title>
                <content>you want to provide a class library of products, and you want to reveal just their interfaces, not their implementations. 
</content>
            </Fragment>
        </Unit>
        <Unit>
            <unitGeneralInformation>
                <identifier>u1012</identifier>
                <title>Structure</title>
                <difficultyLevel>1</difficultyLevel>
            </unitGeneralInformation>
            <Fragment>
                <identifier>f10121</identifier>
                <type>picture_middle</type>
                <detailLevel>1</detailLevel>
                <title>Structure</title>
                <content>AbstractFactory_02</content>
            </Fragment>
        </Unit>
        <Unit>
            <unitGeneralInformation>
                <identifier>u1013</identifier>
                <title>Participants and Collaborations</title>
                <difficultyLevel>1</difficultyLevel>
            </unitGeneralInformation>
            <Fragment>
                <identifier>f10131</identifier>
                <type>first</type>
                <detailLevel>1</detailLevel>
                <title>Participants</title>
                <content> </content>
            </Fragment>
            <Fragment>
                <identifier>f10132</identifier>
                <type>list</type>
                <detailLevel>1</detailLevel>
                <title>Participants</title>
                <content>AbstractFactory (WidgetFactory) </content>
            </Fragment>
            <Fragment>
                <identifier>f10133</identifier>
                <type>list2</type>
                <detailLevel>2</detailLevel>
                <title>Participants</title>
                <content>declares an interface for operations that create abstract product objects. 
</content>
            </Fragment>
            <Fragment>
                <identifier>f10134</identifier>
                <type>list</type>
                <detailLevel>1</detailLevel>
                <title>Participants</title>
                <content>ConcreteFactory (MotifWidgetFactory, PMWidgetFactory) </content>
            </Fragment>
            <Fragment>
                <identifier>f10135</identifier>
                <type>list2</type>
                <detailLevel>2</detailLevel>
                <title>Participants</title>
                <content>implements the operations to create concrete product objects. 
</content>
            </Fragment>
            <Fragment>
                <identifier>f10136</identifier>
                <type>list</type>
                <detailLevel>1</detailLevel>
                <title>Participants</title>
                <content>AbstractProduct (Window, ScrollBar) </content>
            </Fragment>
            <Fragment>
                <identifier>f10137</identifier>
                <type>list2</type>
                <detailLevel>2</detailLevel>
                <title>Participants</title>
                <content>declares an interface for a type of product object. 
</content>
            </Fragment>
            <Fragment>
                <identifier>f10138</identifier>
                <type>list</type>
                <detailLevel>1</detailLevel>
                <title>Participants</title>
                <content>ConcreteProduct (MotifWindow, MotifScrollBar) </content>
            </Fragment>
            <Fragment>
                <identifier>f10139</identifier>
                <type>list2</type>
                <detailLevel>2</detailLevel>
                <title>Participants</title>
                <content>defines a product object to be created by the corresponding concrete factory. </content>
            </Fragment>
